"""empty message

Revision ID: cd049f8cc561
Revises: 6871e62553d0
Create Date: 2022-10-27 13:11:55.828712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd049f8cc561'
down_revision = '6871e62553d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example_models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('string_attribute', sa.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
